/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gradlebuild.identity.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFile
import org.gradle.api.provider.Property
import org.gradle.api.provider.Provider
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

/**
 * Generates a Maven-style `pom.properties` resource for a Gradle module so that
 * Maven-aware tooling (SBOM generators, classpath inspectors, security scanners)
 * can identify the artifact a distribution jar belongs to.
 *
 * The file is written at the Maven-canonical path
 * `META-INF/maven/<groupId>/<artifactId>/pom.properties`. The `groupId` is used
 * verbatim as a single path segment (dots are not turned into directories), matching
 * Maven's own layout.
 *
 * The content is deterministic — only a static header comment plus the three
 * load-bearing keys, with no timestamp — so it does not break the reproducible
 * archives the distribution jars are built with.
 */
@DisableCachingByDefault(because = "Not worth caching")
abstract class GeneratePomProperties : DefaultTask() {

    @get:Input
    abstract val groupId: Property<String>

    @get:Input
    abstract val artifactId: Property<String>

    @get:Input
    abstract val version: Property<String>

    @get:OutputDirectory
    abstract val destinationDirectory: DirectoryProperty

    /**
     * The path of the generated file, relative to the jar root. Suitable as the jar
     * entry name when adding the file to a jar that is assembled manually.
     */
    @get:Internal
    val pomPropertiesEntryPath: Provider<String>
        get() = groupId.zip(artifactId) { group, artifact -> entryPathFor(group, artifact) }

    /**
     * The generated `pom.properties` file itself, for consumers that need the single
     * file rather than the whole output directory.
     */
    @get:Internal
    val pomPropertiesFile: Provider<RegularFile>
        get() = destinationDirectory.file(pomPropertiesEntryPath)

    @TaskAction
    fun generate() {
        val group = groupId.get()
        val artifact = artifactId.get()
        val target = destinationDirectory.file(entryPathFor(group, artifact)).get().asFile
        target.parentFile.mkdirs()
        // Written explicitly (rather than via java.util.Properties) to keep Maven's
        // key order, use '\n' line endings, and avoid the date comment Properties#store
        // emits, which would break archive reproducibility.
        target.writeText(
            buildString {
                append("#Generated by Gradle\n")
                append("groupId=").append(group).append('\n')
                append("artifactId=").append(artifact).append('\n')
                append("version=").append(version.get()).append('\n')
            },
            Charsets.UTF_8
        )
    }

    private
    fun entryPathFor(group: String, artifact: String) =
        "META-INF/maven/$group/$artifact/pom.properties"
}
