/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gradlebuild.packaging

import gradlebuild.identity.tasks.GeneratePomProperties
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File
import java.util.Properties


class GeneratePomPropertiesTest {

    @TempDir
    private
    lateinit var temporaryFolder: File

    @Test
    fun `writes pom_properties at the maven-canonical path`() {
        val task = generate("org.gradle", "gradle-base-services", "9.7.0")

        val pomProperties = File(task.destinationDirectory.get().asFile, "META-INF/maven/org.gradle/gradle-base-services/pom.properties")
        assertTrue(pomProperties.isFile, "Expected pom.properties at the canonical path")
    }

    @Test
    fun `keeps the groupId as a single path segment`() {
        val task = generate("org.gradle", "gradle-core", "9.7.0")

        // Maven uses the groupId verbatim; dots must not become directories.
        assertTrue(File(task.destinationDirectory.get().asFile, "META-INF/maven/org.gradle").isDirectory)
    }

    @Test
    fun `contains exactly the three load-bearing keys`() {
        val task = generate("org.gradle", "gradle-launcher", "9.7.0")

        val properties = task.pomPropertiesFile.get().asFile.reader().use { Properties().apply { load(it) } }
        assertEquals("org.gradle", properties["groupId"])
        assertEquals("gradle-launcher", properties["artifactId"])
        assertEquals("9.7.0", properties["version"])
        assertEquals(3, properties.size)
    }

    @Test
    fun `output is deterministic across runs`() {
        val first = generate("org.gradle", "gradle-core-api", "9.7.0").pomPropertiesFile.get().asFile.readBytes()
        val second = generate("org.gradle", "gradle-core-api", "9.7.0").pomPropertiesFile.get().asFile.readBytes()

        assertTrue(first.contentEquals(second), "pom.properties must be byte-identical across runs")
    }

    @Test
    fun `uses a static header and no timestamp`() {
        val text = generate("org.gradle", "gradle-core", "9.7.0").pomPropertiesFile.get().asFile.readText()

        assertEquals(
            "#Generated by Gradle\ngroupId=org.gradle\nartifactId=gradle-core\nversion=9.7.0\n",
            text,
        )
    }

    @Test
    fun `writes the version verbatim, including full qualified versions`() {
        val properties = generate("org.gradle", "gradle-core", "9.8.0-milestone-2")
            .pomPropertiesFile.get().asFile.reader().use { Properties().apply { load(it) } }

        assertEquals("9.8.0-milestone-2", properties["version"])
    }

    private
    fun generate(groupId: String, artifactId: String, version: String): GeneratePomProperties {
        val project = ProjectBuilder.builder().withProjectDir(temporaryFolder).build()
        val task = project.tasks.register("generatePomProperties", GeneratePomProperties::class.java) {
            this.groupId.set(groupId)
            this.artifactId.set(artifactId)
            this.version.set(version)
            destinationDirectory.set(project.layout.buildDirectory.dir("pom"))
        }.get()
        task.generate()
        return task
    }
}
